name: Daily Update
on:
  schedule:
    - cron: '0 11 * * *' # run at 11am UTC

jobs:
  run_my_code:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        # Main workflow
        - name: Run main
          run: python main.py --update --num-sims 1000

        - name: Commit and push if there are changes
          run: |
            git config --global user.email "bot@invalid.email"
            git config --global user.name "GitHub Action Bot"
            git add .
            git commit -m "Automated data update" || exit 0   # This exits with 0 if there's nothing to commit
            git push --force
