name: Daily Update
on:
  schedule:
    - cron: '0 */4 * * *'  # runs at 12 PM (noon) UTC, which is 7 AM Central Daylight Time

jobs:
  run_my_code:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        # Main workflow
        - name: Run main
          run: python main.py

        - name: Commit and push if there are changes
          run: |
            git config --global user.email "kylecox2000@gmail.com"
            git config --global user.name "xocelyk"
            git add .
            git commit -m "Automated data update" || exit 0   # This exits with 0 if there's nothing to commit
            git push --force
